[project]
name = "llm-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PeterDunlop", email = "petersimondunlop1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
llm-testing = "llm_testing.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"